import { builtinModules } from "node:module";
import esbuild from "rollup-plugin-esbuild";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import rollupJson from "@rollup/plugin-json";
import commonjs from "@rollup/plugin-commonjs";

const isProd = process.env.BUILD === "production";
const externalModules = [
  "obsidian",
  "electron",
  ...builtinModules,
  ...builtinModules.map((moduleName) => `node:${moduleName}`),
];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/

`;

export default {
  input: "src/main.ts",
  output: {
    dir: "dist",
    sourcemap: "inline",
    sourcemapExcludeSources: isProd,
    format: "cjs",
    exports: "default",
    banner,
  },
  external: externalModules,
  plugins: [
    esbuild({
      target: "es2021",
      sourceMap: true,
    }),
    nodeResolve({ browser: false, preferBuiltins: true }),
    rollupJson(),
    commonjs({ sourceMap: false }),
  ],
  onwarn(warning, warn) {
    // workaround to prevent rollup build error
    if (
      warning.code === "EVAL" &&
      /.*\/node_modules\/file-type\/.*/.test(warning.loc?.file ?? "")
    ) {
      return;
    }
    warn(warning);
  },
};
