import esbuild from "rollup-plugin-esbuild";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import rollupJson from "@rollup/plugin-json";
import commonjs from "@rollup/plugin-commonjs";

const isProd = process.env.BUILD === "production";
const externalModules = [
  "obsidian",
];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/

`;

export default {
  input: "src/main.ts",
  output: {
    dir: "dist",
    sourcemap: "inline",
    sourcemapExcludeSources: isProd,
    format: "cjs",
    exports: "default",
    banner,
  },
  external: externalModules,
  plugins: [
    esbuild({
      target: "es2021",
      sourceMap: true,
    }),
    nodeResolve({ browser: true, preferBuiltins: false }),
    rollupJson(),
    commonjs({ sourceMap: false }),
  ],
  onwarn(warning, warn) {
    warn(warning);
  },
};
